- app/models/Contribution.scala
- test/controllers/CalculatorControllerSpec.scala
- test/models/ContributionSpec.scala
- test/models/PensionResultSpec.scala
Updated Contribution object to have a start tax period and end tax period instead of a simple tax year. Updated all unit tests as a consequence.
> Paac 114: Tax period support added.

- app/models/Contribution.scala
- test/models/ContributionSpec.scala
> PAAC-114: Converted Short to Int for TaxPeriod.

- app/logic/PensionAllowanceCalculator.scala
- app/models/Contribution.scala
- app/models/PensionResult.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
- test/models/PensionResultSpec.scala
Also implemented helper apply method on Contribution to make form mapping easier.
> PAAC-129: Updated calculations for carry forward amounts for tax years prior to 2014.

- app/logic/PensionAllowanceCalculator.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
Also now supports chargeable amount values in calculation results.
> PAAC-130: Rolls PAAC-151 and PAAC-152 into this branch.

- app/logic/PensionAllowanceCalculator.scala
- app/logic/Pre2014Calculator.scala
Updated calculator factory object to select correct calculator object based on find/issupported rather than match with literals.
> PAAC-130: Updated calculator factory object 

- app/models/Contribution.scala
- it/ControllerITSpec.scala
- test/models/ContributionSpec.scala
> PAAC-130: Removed code no longer required by front-end.

- app/logic/Pre2014Calculator.scala
- app/logic/Year2014Calculator.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
- test/logic/Pre2014CalculatorSpec.scala
- test/logic/Year2014CalculatorSpec.scala
Implemented boundary tests for both pension allowance calculators.
Added scala check for calculation properties.
> PAAC-155: Implemented boundary tests.

- app/logic/BasicCalculator.scala
- app/logic/CalculatorFactory.scala
- app/logic/PensionAllowanceCalculator.scala
- project/MicroServiceBuild.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
- test/models/PensionResultSpec.scala
Improved code coverage.
Refactored some code for easier maintenance.
> PAAC-158: Added test for negative defined benefit values.

- .gitignore
- app/logic/BasicCalculator.scala
- app/logic/Year2015Period1Calculator.scala
- app/logic/Year2015Period2Calculator.scala
- app/models/Contribution.scala
- app/models/PensionResult.scala
- conf/application.conf
- test/logic/CalculationsSpec.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
- test/logic/Year2015Period2CalculatorSpec.scala
Now works as per https://docs.google.com/spreadsheets/d/1W14DzxdyOIWHarnEf5p8FF3V0Pn84cSjmMLHW9C0oc8.
> PAAC-207: Updated period 1 and period 2 calculators as per QA spreadsheet.

- app/logic/PensionAllowanceCalculator.scala
- app/logic/Year2015Period1Calculator.scala
- app/models/Contribution.scala
- test/logic/CalculationsSpec.scala
- test/logic/PensionAllowanceCalculatorSpec.scala
- test/logic/Utilties.scala
- test/logic/Year2015Period1CalculatorSpec.scala
Refactored calculation tests to use table of strings so to make comparison with spreadsheet easier and the tests more understandable.
> PAAC-207: Fixed cumulative carry forward

- app/calculators/PensionAllowanceCalculator.scala
- app/models/Contribution.scala
- test/calculators/PensionAllowanceCalculatorSpec.scala
- test/calculators/results/Pre2014CalculatorSpec.scala
- test/controllers/CalculatorControllerSpec.scala
- test/models/ContributionSpec.scala
Additionally made earliest supported year 2008.
> PAAC-378: Create pre-trigger contributions if only trigger contributions supplied.

- app/calculators/PensionAllowanceCalculator.scala
- app/calculators/periods/Group3P2Calculator.scala
- app/controllers/CalculatorController.scala
- test/assets/calculators/group3/29.txt
- test/calculators/PensionAllowanceCalculatorSpec.scala
Moved trigger row collapse from frontend to backend service.
Added tests.
> PAAC-386: Fixed group 3 unused allowance.

- app/calculators/PensionAllowanceCalculator.scala
- app/controllers/CalculatorController.scala
- app/models/Request.scala
- test/calculators/PensionAllowanceCalculatorSpec.scala
- test/controllers/CalculatorControllerSpec.scala
- test/models/RequestSpec.scala
Implemented a CalculationRequest to supply parameters to the calculation service.
Updated tests.
> PAAC-439: Calculations now only begin carry forward from a requested year.

- app/calculators/periods/Group3P2Calculator.scala
- app/models/PensionResult.scala
- test/calculators/periods/Group3P2CalculatorSpec.scala
- test/models/PensionResultSpec.scala
Fixed minor error in unused AAA calculation in period 2.
> PAAC-438: Updated models to shuttle isMPA flag from PAAC to PAAC-FRONTEND.

- app/calculators/periods/Period1Calculator.scala
- app/calculators/periods/Period2Calculator.scala
- test/calculators/Group2CalculationsSpec.scala
- test/calculators/periods/Period2CalculatorSpec.scala
Fixed missing mpa value in period 2.
> PAAC-483: Optimised period calculators.

- README.md
- app/calculators/PensionAllowanceCalculator.scala
- app/calculators/internal/Period2Calculator.scala
- app/calculators/internal/TaperedAllowanceCalculator.scala
- app/calculators/internal/package.scala
- app/models/PensionPeriod.scala
- test/calculators/internal/Period2CalculatorSpec.scala
- test/calculators/internal/TaperedAllowanceCalculatorSpec.scala
- test/calculators/results/Post2015CalculatorSpec.scala
- test/calculators/results/Pre2014CalculatorSpec.scala
- test/calculators/results/Year2014CalculatorSpec.scala
- test/calculators/results/Year2015Period1CalculatorSpec.scala
- test/calculators/results/Year2015Period2CalculatorSpec.scala
- test/models/CalculatorOutputsSpec.scala
Implemented unused allowance and exceeding AA.
Fixed error in provideMissingYearContributions method in PensionAllowanceCalculator.
> PAAC-154: Implemented annual allowance with carry forwards and cumulative carry forwards.

- app/calculators/internal/Period1Calculator.scala
- app/calculators/internal/Period2Calculator.scala
- app/calculators/internal/TaperedAllowanceCalculator.scala
- test/calculators/internal/TaperedAllowanceCalculatorSpec.scala
Ensure isACA doesn't return true when dca == aca.
> PAAC-605: Updated taper allowance DCA calculations.

- app/calculators/PensionAllowanceCalculator.scala
- app/calculators/internal/Period1Calculator.scala
- app/calculators/internal/Period2Calculator.scala
- app/calculators/internal/TaperedAllowanceCalculator.scala
- app/calculators/internal/package.scala
- app/calculators/results/ExtendedCalculator.scala
- test/assets/calculators/group3/30.txt
- test/calculators/results/Year2015Period1CalculatorSpec.scala
> PAAC-646: Fixes for AACCF for tapered and period 1/2 calculators.

- app/calculators/internal/Period2Calculator.scala
> PAAC-687: Ensure only AAA or MAXAACF are only subtracted when user is not a member in period 1.

- app/config/ApplicationGlobal.scala
- app/controllers/CalculatorController.scala
- app/metrics/Metrics.scala
- conf/application.conf
- conf/play.plugins
- conf/prod.routes
- project/MicroService.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
- test/calculators/CalculationsSpec.scala
- test/calculators/PensionAllowanceCalculatorSpec.scala
- test/calculators/TestUtilities.scala
- test/calculators/internal/TaperedAllowanceCalculatorSpec.scala
- test/calculators/results/Post2015CalculatorSpec.scala
- test/controllers/CalculatorControllerSpec.scala
- test/metrics/MetricsSpec.scala
- test/models/CalculatorInputsSpec.scala
> DDCNLS-380

- conf/application.conf
Also set httpOnly flag to true to prevent security issues.
> DDCNLS-380: Added application secret to application.conf

- project/build.properties
DDCNLS-1381: Upgraded sbt version to 0.13.15
> DDCNLS-1381: Upgraded sbt version to 0.13.15
